import React from 'react';
import { useLanguage } from '../../contexts/LanguageContext';

const CommissionExplainer: React.FC = () => {
  const { t } = useLanguage();

  return (
    <div className="commission-explainer-section">
      <h2 className="commission-explainer-title">Commission Structure</h2>
      <p className="commission-explainer-subtitle">
        Earn competitive commissions on every trade plus bonus Crystal points
      </p>
      <div className="commission-cards">
        <div className="commission-card">
          <div className="commission-card-header">
            <h3>Trading Fee Commission</h3>
            <div className="commission-badge">Base Tier</div>
          </div>
          <div className="commission-card-body">
            <div className="commission-rate">10%+</div>
            <p className="commission-description">
              Earn 10% or more of all trading fees generated by your referrals
            </p>
            <div className="commission-formula">
              <span className="formula-label">Formula:</span>
              <code>Your Earnings = Referral Trading Fees × 10%</code>
            </div>
            <div className="commission-example">
              <span className="example-label">Example:</span>
              <p>If your referral trades $100,000 with 0.05% fees ($50), you earn $5</p>
            </div>
          </div>
        </div>

        <div className="commission-card highlighted">
          <div className="commission-card-header">
            <h3>Crystal Points Multiplier</h3>
            <div className="commission-badge premium">Bonus</div>
          </div>
          <div className="commission-card-body">
            <div className="commission-rate">1.5x</div>
            <p className="commission-description">
              Boost your Crystal points earnings with a 1.5x multiplier on referral activity
            </p>
            <div className="commission-formula">
              <span className="formula-label">Formula:</span>
              <code>Your Points = Base Points × 1.5</code>
            </div>
            <div className="commission-example">
              <span className="example-label">Example:</span>
              <p>If you normally earn 100 points, you'll earn 150 points from referral trades</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommissionExplainer;
