import React, { useState } from 'react';
import { useLanguage } from '../../contexts/LanguageContext';

interface FAQItem {
  question: string;
  answer: string;
}

const ReferralFAQ: React.FC = () => {
  const { t } = useLanguage();
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqItems: FAQItem[] = [
    {
      question: 'What is the Crystal Affiliate Program?',
      answer: 'The Crystal Affiliate Program allows you to earn lifetime commissions by referring traders to Crystal Exchange. You receive a percentage of trading fees generated by your referrals, plus bonus Crystal points with a 1.5x multiplier.'
    },
    {
      question: 'How do I join the affiliate program?',
      answer: 'Only screened users can generate referral codes. Connect your wallet and apply for an affiliate code. Once approved, you can immediately start sharing your unique referral link and earning commissions.'
    },
    {
      question: 'What are the commission rates?',
      answer: 'Base commission starts at 10% of trading fees generated by your referrals. As you progress through tiers (Bronze → Silver → Gold), you can unlock higher commission rates up to 25% plus increased Crystal points multipliers.'
    },
    {
      question: 'Is there a minimum payout amount?',
      answer: 'No! There are no minimum thresholds. You can claim your earnings instantly on-chain at any time, regardless of the amount. All payouts are processed immediately via smart contract.'
    },
    {
      question: 'How can I track my referrals and earnings?',
      answer: 'Your affiliate dashboard provides real-time analytics including total referrals, commission earned, claimable fees, and historical performance charts. You can track individual referral activity and monitor your tier progression.'
    },
    {
      question: 'Do my referrals expire?',
      answer: 'Never! Once someone uses your referral code, they are linked to you for life. You will continue earning commissions on all their future trades indefinitely with no expiration.'
    },
    {
      question: 'What marketing tools do you provide?',
      answer: 'Affiliates get access to QR codes for easy sharing, downloadable social media badges, promotional copy templates, and performance banners. More advanced asset packs and tracking tools are coming soon.'
    },
    {
      question: 'How does the tier system work?',
      answer: 'You start at Bronze tier and progress to Silver (50+ referrals) and Gold (100+ referrals). Each tier unlocks higher commission rates, increased point multipliers, and exclusive benefits. Your tier is calculated automatically based on your total referral count.'
    }
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="referral-faq-section">
      <h2 className="referral-faq-title">Frequently Asked Questions</h2>
      <p className="referral-faq-subtitle">
        Everything you need to know about our affiliate program
      </p>
      <div className="referral-faq-list">
        {faqItems.map((item, index) => (
          <div key={index} className={`faq-item ${openIndex === index ? 'open' : ''}`}>
            <button
              className="faq-question"
              onClick={() => toggleFAQ(index)}
            >
              <span>{item.question}</span>
              <span className="faq-toggle-icon">
                {openIndex === index ? '−' : '+'}
              </span>
            </button>
            {openIndex === index && (
              <div className="faq-answer">
                <p>{item.answer}</p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReferralFAQ;
