import React from 'react';
import { TrendingUp } from 'lucide-react';

interface ReferralTierProps {
  commissionBonus: number;
}

interface TierInfo {
  name: string;
  color: string;
  rate: string;
  multiplier: string;
  minCrystals: number;
  next: {
    name: string;
    needed: number;
    minCrystals: number;
  } | null;
}

const ReferralTier: React.FC<ReferralTierProps> = ({ commissionBonus }) => {
  const getTierInfo = (crystals: number): TierInfo => {
    if (crystals >= 500) {
      return {
        name: 'Gold',
        color: '#FFD700',
        rate: '25%',
        multiplier: '2x',
        minCrystals: 500,
        next: null,
      };
    }
    if (crystals >= 200) {
      return {
        name: 'Silver',
        color: '#C0C0C0',
        rate: '20%',
        multiplier: '1.5x',
        minCrystals: 200,
        next: {
          name: 'Gold',
          needed: 500 - crystals,
          minCrystals: 500,
        },
      };
    }
    return {
      name: 'Bronze',
      color: '#CD7F32',
      rate: '15%',
      multiplier: '1.25x',
      minCrystals: 0,
      next: {
        name: 'Silver',
        needed: 200 - crystals,
        minCrystals: 200,
      },
    };
  };

  const tier = getTierInfo(commissionBonus);
  const progressPercentage = tier.next
    ? ((commissionBonus - tier.minCrystals) /
        (tier.next.minCrystals - tier.minCrystals)) *
      100
    : 100;

  return (
    <div className="tier-section">
      <div className="tier-header">
        <div className="tier-header-left">
          <h3 className="tier-title">{commissionBonus} Crystals from Referrals</h3>
          <div className="tier-badge" style={{ backgroundColor: tier.color }}>
            <TrendingUp size={16} />
            <span className="tier-badge-name">{tier.name}</span>
          </div>
        </div>
        {tier.next && (
          <div className="tier-next-info">
            <span className="tier-next-label">Next Tier:</span>
            <span className="tier-next-name">{tier.next.name}</span>
          </div>
        )}
      </div>

      {tier.next && (
        <div className="tier-progress">
          <div className="tier-progress-bar">
            <div
              className="tier-progress-fill"
              style={{
                width: `${progressPercentage}%`,
                backgroundColor: tier.color,
              }}
            />
          </div>
          <p className="tier-progress-text">
            {commissionBonus} / {tier.next.minCrystals}
          </p>
        </div>
      )}

      {tier.next === null && (
        <div className="tier-max-message">
          <p className="tier-max-text">
            🎉 You've reached the highest tier! Keep growing your network.
          </p>
        </div>
      )}

      <div className="tier-benefits">
        <div className="tier-benefit-card">
          <span className="tier-benefit-label">Commission Rate</span>
          <span className="tier-benefit-value" style={{ color: tier.color }}>
            {tier.rate}
          </span>
          <span className="tier-benefit-description">
            of trading fees generated by referrals
          </span>
        </div>
        <div className="tier-benefit-card">
          <span className="tier-benefit-label">Points Multiplier</span>
          <span className="tier-benefit-value" style={{ color: tier.color }}>
            {tier.multiplier}
          </span>
          <span className="tier-benefit-description">
            boost on Crystal points earned
          </span>
        </div>
        <div className="tier-benefit-card">
          <span className="tier-benefit-label">Referral Bonus</span>
          <span className="tier-benefit-value" style={{ color: tier.color }}>
            {tier.name === 'Gold'
              ? '5%'
              : tier.name === 'Silver'
              ? '3%'
              : '2%'}
          </span>
          <span className="tier-benefit-description">
            of your referrals' Crystal earnings
          </span>
        </div>
      </div>

      <div className="tier-requirements">
        <h4 className="tier-requirements-title">Tier Requirements</h4>
        <div className="tier-requirements-list">
          <div
            className={`tier-requirement-item ${
              commissionBonus >= 0 ? 'achieved' : ''
            }`}
          >
            <div className="tier-requirement-badge bronze">Bronze</div>
            <div className="tier-requirement-details">
              <span className="tier-requirement-refs">0+ Crystals</span>
              <span className="tier-requirement-benefits">
                15% rate • 1.25x multiplier
              </span>
            </div>
          </div>
          <div
            className={`tier-requirement-item ${
              commissionBonus >= 200 ? 'achieved' : ''
            }`}
          >
            <div className="tier-requirement-badge silver">Silver</div>
            <div className="tier-requirement-details">
              <span className="tier-requirement-refs">200+ Crystals</span>
              <span className="tier-requirement-benefits">
                20% rate • 1.5x multiplier
              </span>
            </div>
          </div>
          <div
            className={`tier-requirement-item ${
              commissionBonus >= 500 ? 'achieved' : ''
            }`}
          >
            <div className="tier-requirement-badge gold">Gold</div>
            <div className="tier-requirement-details">
              <span className="tier-requirement-refs">500+ Crystals</span>
              <span className="tier-requirement-benefits">
                25% rate • 2x multiplier
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReferralTier;
