export const defaultMetrics = {
  price: 0.000083878,
  mini: [],
  change24h: 0,
  volume24h: 0,
  holders: 0,
  proTraders: 0,
  kolTraders: 0,
  sniperHolding: 0,
  devHolding: 0,
  bundleHolding: 0,
  insiderHolding: 0,
  top10Holding: 0,
  buyTransactions: 0,
  sellTransactions: 0,
  globalFeesPaid: 0,
  progress: 0,
  status: 'new' as const,
  created: '0h ago',
  bondingAmount: 0,
};
